### ISSUE TITLE
SystemC config is missing

### ISSUE THREAD

**Issue by tamimcse** [andrewboutros/rad-flow#3]
Hi 

I am getting following error. Could you please advise how to fix it?

```
....../rad-flow/rad-sim/build$ cmake ..
CMake Error at sim/CMakeLists.txt:2 (find_package):
  Could not find a package configuration file provided by "SystemCLanguage"
  with any of the following names:

    SystemCLanguageConfig.cmake
    systemclanguage-config.cmake

  Add the installation prefix of "SystemCLanguage" to CMAKE_PREFIX_PATH or
  set "SystemCLanguage_DIR" to a directory containing one of the above files.
  If "SystemCLanguage" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by andrewboutros** [comment]
Hi @tamimcse,

Sorry for the slow response. I had to find a new machine to have a fresh setup of RAD-Sim to reproduce your error and write a setup guide for the flow.

Here is a link to the complete setup steps (I have also linked to it in the main repo README): [Setting Up RAD-Sim](https://funny-beach-0da.notion.site/Setting-Up-RAD-Sim-c9748d28ab954f4e8aa00cae46b8cba2). You will need to follow the steps for installing SystemC to resolve your error. Also, please download the latest SystemC tarball (2.3.4) and pull the latest commit to the repo to match these steps.

Let me know if the issue is resolved.

Thanks,
-Andrew
